### PR TITLE
Only use ajava files produced in last iteration during WPI

### PR DESCRIPTION
**Pull request by kelloggm**
typetools/checker-framework#5091 introduces a new ambiguity error when more than one valid ajava file is passed for a single source file. This change affects the DLJC wpi tool, because it produces several iterations of ajava files. This change modifies the wpi tool to only use the most recent iteration, rather than using all iterations at once.

### CODE REVIEW

**Review by mernst — APPROVED** [review]

**Comment by mernst** [comment]
@kelloggm Could you take a look at the tests, which are timing out?

**Review by mernst — COMMENTED** [review]
CI is failing with this output:

```
Comparing /tmp/runner/checker-framework/checker/bin-devel/wpi-plumelib/bcel-util.expected /tmp/wpi-plumelib-tests-20220328-194017-Feh/bcel-util/dljc-out/typecheck.out in /tmp/wpi-plumelib-tests-20220328-194017-Feh/bcel-util
--- expected.txt	2022-03-28 19:43:30.580567327 +0000
+++ actual.txt	2022-03-28 19:43:30.592567188 +0000
@@ -1,7 +1,7 @@
 warning: No processor claimed any of these annotations: org.checkerframework.checker.nullness.qual.EnsuresNonNull,org.checkerframework.checker.nullness.qual.RequiresNonNull
-BcelUtil.java:786: error: [argument] incompatible argument for parameter typename of parseFqBinaryName.
-        Signatures.ClassnameAndDimensions.parseFqBinaryName(classname);
-                                                            ^
-  found   : @SignatureUnknown String
-  required: @FqBinaryName String
+SimpleLog.java:136: error: [contracts.precondition] precondition of getIndentString is not satisfied.
+        logfile.printf("%s  %s%n", getIndentString(), ste);
+                                                  ^
+  found   : no information about this.filename
+  required: this.filename is @Nullable
 1 error
```

**Comment by kelloggm** [comment]
> CI is failing with this output

This failure has been fixed (in https://github.com/typetools/checker-framework/pull/5095), so CI just needed to be re-run.
